version: '3.4'

services:
  boilerplate-react:
    image: boilerplate-react
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.development
    volumes:
      - './:/app'
    network_mode: "host"